#!/usr/bin/env bash

# All Unikorn components use the same build system, so can be built in a generic
# manner.  This does the build and pushes it into KinD.
#
# NOTE: must be run from the compenent's root directory.

CHART="$(ls charts)"
CHART_META="charts/${CHART}/Chart.yaml"

if [[ "$(uname)" == "Darwin" ]]; then
	MAKECMD="gmake"
else
	MAKECMD="make"
fi

$MAKECMD images-kind-load VERSION="$(yq .version "${CHART_META}")"
