#!/bin/bash

# Deploys a unikorn component.  Will only work if the chart version
# has been bumped, otherwise you will need to manually restart all
# the pods with kubectl.
#
# NOTE: must be run from the compenent's root directory.

# Get the environemnt.
# TODO: getopts
ENVIRONMENT="local"

# A prefix to add to namespaces to avoid clashes
# TODO: getopts
NAMESPACE_PREFIX="unikorn"

# Figure out some repo constants.
REPO=$(basename "$(pwd)")
CHARTDIR="charts/${REPO}"
CRDDIR="${CHARTDIR}/crds"

# Define some constants for Helm
NAMESPACE="${NAMESPACE_PREFIX}-${REPO}"

# Update CRDs if necessary, helm won't do this for you.
if [[ -d ${CRDDIR} ]]; then
	kubectl apply -f "${CRDDIR}"
fi

ARGS=()

# Add an values files you need.
VALUESFILE="${HOME}/.config/unikorn/${ENVIRONMENT}/${REPO}.yaml"

if [[ -f ${VALUESFILE} ]]; then
	ARGS+=("-f" "${VALUESFILE}")
fi

# Deploy the actual chart.
helm upgrade --install --create-namespace -n "${NAMESPACE}" "${REPO}" "${CHARTDIR}" "${ARGS[@]}"
