#!/usr/bin/env bash

# Restarts a unikorn component.  Gets more hardcore than the deploy
# command when you've not mdified anything that would cause a pod
# restart.
#
# NOTE: must be run from the compenent's root directory.

# A prefix to add to namespaces to avoid clashes
# TODO: getopts
NAMESPACE_PREFIX="unikorn"

# Figure out some repo constants.
REPO=$(basename "$(pwd)")

# Define some constants for Helm
NAMESPACE="${NAMESPACE_PREFIX}-${REPO}"

# Do any specializations.
kubectl delete pod --namespace "${NAMESPACE}" --all --now
