#!/bin/bash

# Restarts a unikorn component.  Gets more hardcore than the deploy
# command when you've not mdified anything that would cause a pod
# restart.
#
# NOTE: must be run from the compenent's root directory.

# Grab the repository.
REPO=$(basename "$(pwd)")

# Do any specializations.
case ${REPO} in
        core)
                NAMESPACE=unikorn
                ;;
        identity)
                NAMESPACE=unikorn-identity
                ;;
        unikorn)
                NAMESPACE=unikorn
                ;;
        ui)
                NAMESPACE=unikorn-ui
                ;;
        *)
                echo "Unrecognized repo ${REPO}"
                exit 1
                ;;
esac

kubectl delete pod --namespace ${NAMESPACE} --all --now
